name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Project
        run: |
          cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: veoc-${{ matrix.os }}
          path: |
            build/anvil
            build/anvil.exe
            build/${{ matrix.build_type }}/anvil.exe
          if-no-files-found: error
